# API Configurations
api:
  name: "${project.artifactId}"
  version: "${project.version}"
  #Replace with respective autodiscovery id
  autodiscoveryID: "16422509"
  
# Listener configuration  
https:
  host: "0.0.0.0"
  port: "8082"
  
# API Configuration
store-api:
  http-listener:
    path: "/api/*"

# MySQL configuration
mysql:
  host: "localhost"
  port: "3306"
  user: "fortifymule"
  password: "fortifymule"
  
# TLS configuration
tls:
    keyStorepass: "password"
    password: "password"
    
# Customize the application messages in the below section
application-msgs:
  #Local Exception logger message
  local-exception-handler-message: "Exception has occured"
  success-flag: "true"
