#%RAML 1.0
title: Products API
version: v1.0

securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
    describedBy:
      headers:
        Authorization: 
          description: Base64-encoded "username:password"
        type: string
      responses:
        401:
          description: |
            Unauthorized: username or password or the combination is invalid
          
securedBy: [basic]

types:
  product:
    properties:
      id: string
      code: string
      name: string
      summary: string
      description: string
      image: string
      price: number
      onSale: boolean
      salePrice: number
      inStock: boolean
      timeToStock: number
      rating: number
      available: boolean
  stock:
    properties:
      productId: string
      quantity: number
      
/products:
      get:
        responses: 
          200:
            body:
              application/json:
                type: product[]
                examples: 
                  output: !include examples/products.json
/products/{productId}:
      uriParameters:
        productId: string
      get:
        responses: 
          200:
            body:
              application/json:
                type: product
                examples: 
                  output: !include examples/product.json
          404:
            body: 
              application/json:
                properties:
                  message: string
                example: |
                  {
                    "message" : "Product not found"
                  }
/products/{productId}/stockLevel:
      uriParameters:
        productId: string
      get:
        responses: 
          200:
            body:
              application/json:
                type: stock
                examples: 
                  output: !include examples/stock.json
          404:
            body: 
              application/json:
                properties:
                  message: string
                example: |
                  {
                    "message" : "Product not found"
                  }                  