#%RAML 1.0
title: Products API
version: v1.0

securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
    describedBy:
      headers:
        Authorization: 
          description: Base64-encoded "username:password"
        type: string
      responses:
        401:
          description: |
            Unauthorized: username or password or the combination is invalid
          
securedBy: [basic]

types:
  product:
    properties:
      identifier?: string
      identifiers: IdentifierMap
      brand: string
      model: string
      rating: number
      description?: string
      pictures: string[]
      price: price
  
  price:
    properties:
      amount: amount
      salesUnit: salesUnit
      
  amount:
    properties:
      currency: string
      currencyValue: number
      name : string
  
  salesUnit:
    properties:
      code: string
      name: string
  
  Identifier:
    type: string
    pattern: ^[0-9A-Za-z-]+
    minLength: 3
    maxLength: 36

  IdentifierMap:
    type: array
    items:
      type: object
      properties:
        /[0-9A-Z-]+/:
          type: Identifier

/products:
      get:
        responses: 
          200:
            body:
              application/json:
                type: product[]
                examples: 
                  output: !include examples/products.json
/products/{productId}:
      uriParameters:
        productId: string
      get:
        responses: 
          200:
            body:
              application/json:
                type: product
                examples: 
                  output: !include examples/product.json
          404:
            body: 
              application/json:
                properties:
                  message: string
                example: |
                  {
                    "message" : "Product not found"
                  }